import Head from 'next/head'
import React, { useEffect } from 'react'
import cheerio from 'cheerio';
import fetchdata from 'node-fetch';
import { useContext, } from 'react';
import { useRouter } from 'next/router';
import VideoThumbnail from '../components/VideoThumbnail';
import Sidebar from '../components/Sidebar';
import Videos from '../components/Videos';
import videos from "../JsonData/HomePage.json"
import json from "../JsonData/indian.json"
export default function Home() {

console.log(json.videos);

  return (
    <div >
      <Head>
        <title>Desi Porn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className="flex ">
        <Sidebar />

        <Videos data={videos.videos} />
      </main>

      <footer >

      </footer>
    </div>
  )
}


export async function getStaticProps() {
  var dataArray = []

  const scrape = async (url) => {

    var TitleArray = []
    var liked = []
    var disliked = []
    var durationArray = []
    var hrefArray = []
    var thumbnail = []



    const response = await fetchdata(url)
    const body = await response.text();
    const $ = cheerio.load(body)



    $('.info a').each((i, el) => {
      const data = $(el).text().trim();
      TitleArray.push(data)


    })
    $('.info a').each((i, el) => {

      const data = $(el).attr('href')
      hrefArray.push(`https://justindianporn.me${data}`)

    })


    $('.image a img').each((i, el) => {

      const data = $(el).attr('data-src')
      thumbnail.push(data)


    })

    $('.length').each((i, el) => {

      const data = $(el).text().trim();
      durationArray.push(data)

    })
    $('.likes.good').each((i, el) => {

      const data = $(el).text().trim();
      liked.push(data)

    })
    $('.dislikes.bad').each((i, el) => {

      const data = $(el).text().trim();
      disliked.push(data)

    })

    for (let Page = 0; Page < TitleArray.length; Page++) {
      dataArray.push({
        TitleArray: TitleArray[Page],
        liked: liked[Page],
        disliked: disliked[Page],
        durationArray: durationArray[Page],
        hrefArray: hrefArray[Page],
        thumbnail: thumbnail[Page],
      })
    }


  }

  //Data is loaded and saved to local JSON file
  // await scrape(`https://justindianporn.me/`)


console.log(dataArray);
  return {
    props: {
      video_collection: dataArray,
    }
  }
}