import Head from 'next/head'
import { useContext, useEffect, useState } from 'react'
import cheerio from 'cheerio';
import fetchdata from 'node-fetch';

import Sidebar from '../components/Sidebar';
import Videos from '../components/Videos';
import videos from "../JsonData/indian/indian3.json"
import videosContext from '../context/videos/videosContext'

export default function Home() {

  const { setcurrentLocation } = useContext(videosContext);

  useEffect(() => {
    async function fetchData() {
      var location = {}
      if (!localStorage.getItem("location") === null) {
        setcurrentLocation(location)
      }
      else {
        try {
          const response = await fetch('https://geolocation-db.com/json/8dd79c70-0801-11ec-a29f-e381a788c2c0')
          location = await response.json()

        } catch (error) {
          try {
            const response = await fetch('https://geolocation-db.com/json/8dd79c70-0801-11ec-a29f-e381a788c2c0')
            location = await response.json()
            console.log(location);

          } catch (error) {
            location = { country_name: 'india' }
          }
        }
        setcurrentLocation(location)
        localStorage.setItem("location", JSON.stringify(location))
      }
    }

    fetchData()
  }, []);


  return (
    <div >
      <Head>
        <title>Desi Porn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className="flex ">
        <Sidebar />

        <Videos data={videos} />
      </main>

      <footer >

      </footer>
    </div>
  )
}


export async function getStaticProps() {
  var dataArray = []

  const scrape = async (url) => {

    var TitleArray = []
    var liked = []
    var disliked = []
    var durationArray = []
    var hrefArray = []
    var thumbnail = []



    const response = await fetchdata(url)
    const body = await response.text();
    const $ = cheerio.load(body)



    $('.info a').each((i, el) => {
      const data = $(el).text().trim();
      TitleArray.push(data)


    })
    $('.info a').each((i, el) => {

      const data = $(el).attr('href')
      hrefArray.push(`https://justindianporn.me${data}`)

    })


    $('.image a img').each((i, el) => {

      const data = $(el).attr('data-src')
      thumbnail.push(data)


    })

    $('.length').each((i, el) => {

      const data = $(el).text().trim();
      durationArray.push(data)

    })
    $('.likes.good').each((i, el) => {

      const data = $(el).text().trim();
      liked.push(data)

    })
    $('.dislikes.bad').each((i, el) => {

      const data = $(el).text().trim();
      disliked.push(data)

    })

    for (let Page = 0; Page < TitleArray.length; Page++) {
      dataArray.push({
        TitleArray: TitleArray[Page],
        liked: liked[Page],
        disliked: disliked[Page],
        durationArray: durationArray[Page],
        hrefArray: hrefArray[Page],
        thumbnail: thumbnail[Page],
      })
    }


  }

  //Data is loaded and saved to local JSON file
  // await scrape(`https://justindianporn.me/`)


  console.log(dataArray);
  return {
    props: {
      video_collection: dataArray,
    }
  }
}